### ISSUE TITLE
Invert safe check parameters

### ISSUE THREAD

**Issue by Sapo84** [FabulousCupcake/hv-battle-scripts#1]
`if (isEverythingSafe() || !CONFIG.safety.enabled)`
is better written as
`if (!CONFIG.safety.enabled || isEverythingSafe())`
to prevent the function isEverythingSafe from needlessly running when the safety is not enabled.

And since I'm here, why are you using so many for syntaxes? Unless I'm really missing something you should be able to use forEach in every case.
And it's also kind of strange to declare a pattern inside a for loop. I mean, it's probably a 1/100 ms optimization but it still looks very wrong to me.

**Comment by FabulousCupcake** [comment]
Hey!

The safe check is fixed in 82b672b, thanks!

For [this](https://github.com/FabulousCupcake/hv-battle-scripts/blob/ba3b692f1bde8f64cb3ef8efe712bdc644a9a2ba/src/index.js#L187) and [this](https://github.com/FabulousCupcake/hv-battle-scripts/blob/ba3b692f1bde8f64cb3ef8efe712bdc644a9a2ba/src/index.js#L203), I need the index, which is why I didn't use `forEach`. Maybe there's a way to do it without using the usual for loop (and probably make it faster), but I'll take a look on it when I have some time to kill 😉 
Please do submit a merge request if you can find a solution for it 😛 

For [this](https://github.com/FabulousCupcake/hv-battle-scripts/blob/ba3b692f1bde8f64cb3ef8efe712bdc644a9a2ba/src/index.js#L89) `for … of` loop, I'm still finding out if this is faster than converting the `querySelectorAll` to array [like so](https://github.com/FabulousCupcake/hv-battle-scripts/blob/ba3b692f1bde8f64cb3ef8efe712bdc644a9a2ba/src/index.js#L123) so you can iterate it with `forEach`, but again, I'll refactor this when I got the time 😉 

Regarding the variable declaration inside the loop, I like putting the pattern inside the loop because it's easier to read (it's used immediately on the next line), and there is [no performance impact at all](https://jsperf.com/constant-variable-declaration-in-loops/). I'm guessing current javascript engines are clever enough to optimize this kind of issue.

Thanks for the inputs! I really appreciate it! 😄
